### ISSUE TITLE
Feature idea: Ability to cancel outdated actions using a key

### ISSUE THREAD

**Issue by graphicla** [jevakallio/redux-offline#415]
Preface: This is not a bug.

Frequently you perform an action and then perform another action, and the second one cancels out the first. For example, editing a document you might make a change, Save, work for a few more minutes, Save, work a little longer, and Save again. This is potentially three queued requests, the first two of which are made irrelevant by the third.

The idea is to add an optional key property to the offline meta object. A queued action would remove any previously queued actions with the same key.

What do you think?

**Comment by mnightingale** [comment]
I'm facing a similar situation, It looks like queue manipulation is on the roadmap for V3 #392

It's not ideal but I think the existing queue options could be a solution https://github.com/redux-offline/redux-offline/blob/develop/docs/api/config.md#queue
Similar to the example enqueue could use a key to filters the pending actions.

I don't think it quite covers all cases at the moment because you couldn't just cancel a queued action by the key. For instance if you had an UPLOAD action you later wanted to cancel, I think you'd need a kind of NoopAction so that when the queue.enqueue gets called it removes the action you want to cancel and doesn't enqueue the noop action.

**Comment by mnightingale** [comment]
I think I've got what's described above working.

1. Remove any queued actions that match our key
1. Ignore any noop offline effects

```typescript
  const getKey = action => action.meta.offline.effect.key;

  ...

  queue: {
    ...defaultQueue,
    enqueue: (array, item, context) => {
      const key = getKey(item);
      if (key) {
        // Remove any offline actions that already exist for this key
        const newArray = array.filter(action =>
          !(getKey(action) === key)
        );

        // Ignore noop actions
        if (NOOP !== item.meta.offline.effect.type) {
          newArray.push(item);
        }

        return newArray;
      }

      return [...array, item];
    },
  }
```

**Comment by graphicla** [comment]
Thanks for pointing out that configuration option. I ended up with roughly the same function, but did not account for a NOOP action. Perfect solution to the problem.

**Comment by sobrinho** [comment]
Closing since there's a workaround.
