### ISSUE TITLE
Why not PouchDB?

### ISSUE THREAD

**Issue by guettli** [jevakallio/redux-offline#417]
Why do you not use PouchDB?

It seems to solve the same problem: https://pouchdb.com/guides/replication.html#couchdb-sync

**Comment by blwinters** [comment]
Perhaps you want to use a different kind of server or don't have control over the server.

**Comment by guettli** [comment]
I have control over the server. Which tool do you recommend?

**Comment by blwinters** [comment]
I was just saying that people who can't use CouchDB on the server can still use Redux Offline for the client. But my understanding is that using PouchDB for the client requires you to also use it on the server. This difference would be a reason to use Redux Offline instead of PouchDB, but please correct me if I am mistaken.

**Comment by sobrinho** [comment]
As explained, different goals.
