### ISSUE TITLE
Bug: Unable to resolve module `@react-native-community/async-storage` 

### ISSUE THREAD

**Issue by tmirun** [jevakallio/redux-offline#436]
### Bug:

I had this error, when i import this library in react-native

```
Unable to resolve module 
`@react-native-community/async-storage` from `node_modules/@redux-offline/redux-offline/lib/defaults/persist.native.js`: @react-native-community/async-storage could not be found within the project.
```

![image](https://user-images.githubusercontent.com/8052536/112136391-2cbce480-8bcf-11eb-9987-96f283c3e48b.png)

the error is we still use old package `@react-native-community/async-storage`, this is deprecated:

https://www.npmjs.com/package/@react-native-community/async-storage

![image](https://user-images.githubusercontent.com/8052536/112136671-8fae7b80-8bcf-11eb-8a6f-6c1fbf8dd567.png)

**we should update** to `@react-native-async-storage/async-storage`

**Comment by mnightingale** [comment]
Did you install the wrong version? from https://github.com/redux-offline/redux-offline/blob/develop/README.md

> ## Quick start
> 
> ##### 1. Install with npm (or [Yarn](https://yarnpkg.com))
> 
> ##### For React Native 0.60+
> ```shell
> npm install --save @redux-offline/redux-offline@native
> ```

**Comment by joshuadiezmo** [comment]
I also encounter this problem. I follow the installation from https://github.com/redux-offline/redux-offline/blob/develop/README.md but still got the error.

**Comment by tmirun** [comment]
i used final redux-persist library

**Comment by agustiinlombardo** [comment]
Hi! I have the same problem with my application. Some idea about How I can fix it?

**Comment by superyarik** [comment]
face this issue. i see in project, version 2.6.0, in node_modules/@redux-offline/redux-offline/src/defaults/persist.native.js
and see
// $FlowIgnore
import AsyncStorage from '@react-native-community/async-storage'; // eslint-disable-line

but in github
https://github.com/redux-offline/redux-offline/blob/native/src/defaults/persist.native.js

import AsyncStorage from '@react-native-async-storage/async-storage';

wtf?

**Comment by mnightingale** [comment]
There hasn't been a release since the `@react-native-async-storage/async-storage` change was merged, so what's on the native branch doesn't match the published version.

# We can either:

1. Continue to depend on `@react-native-community/async-storage`
2. Wait for @sorodrigo to publish a release
3. Install (and optionally build) from source (a bit messy)
4. Publish a scoped and/or private package

Whichever you do don’t forget to install the external dependencies, I think this package should add them as peerDependencies.

Which ones you need will depend on which approach you take from above.

## To install direct from GitHub

```
npm install --save https://github.com/redux-offline/redux-offline#native
```

peerDependencies

```
npm install --save @react-native-async-storage/async-storage @react-native-community/netinfo
```

## To avoid having to import from /src like:

```
import { offline } from '@redux-offline/redux-offline/src'
```

You could build it, I happen to be on Windows right now and the default build script wont work (`npm run build` tries to use rm) so I had to call babel to build, therefore I modified my projects package.json to have.

```
"scripts": {
    "postinstall": "cd node_modules/@redux-offline/redux-offline && npm install && npx babel src --out-dir lib --ignore '**/__tests__/**'",
    ...
}

**Comment by superyarik** [comment]
@mnightingale thanks! i fork it, add prepare step on scipts and use it from my github.

**Comment by sorodrigo** [comment]
Hello, no need to fork it. Let's talk about bringing someone who can help me maintain this @mnightingale @superyarik . I've onboarded many people throughout the years, but no one stays 😪 .

I'm releasing the new version, apologies to everyone affected.

**Comment by sorodrigo** [comment]
Published under `@native`. https://www.npmjs.com/package/@redux-offline/redux-offline

**Comment by tmirun** [comment]
@sorodrigo thanks

**Comment by oscar-gallog** [comment]
I still have this error, and I have the latest version installed. So... how do you fix this?

**Comment by sorodrigo** [comment]
please check your yarn.lock sometimes it doesnt install the latest one
